# Generated by Django 5.0.4 on 2024-04-15 09:19

import base.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeration_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('grand_father', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True)),
                ('flight_num', models.IntegerField(blank=True, null=True, verbose_name='رقم الرحلة')),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('borading_time', models.TimeField()),
                ('gate_num', models.IntegerField(blank=True, null=True)),
                ('flight_company', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('hotel', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_address', models.CharField(max_length=100)),
                ('room_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('grand_father', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.IntegerField()),
                ('birthday', models.DateField()),
                ('job_position', models.CharField(blank=True, choices=[('موظف حكومي', 'حكومي'), ('موظف شركة', 'موظف'), ('موظف أهلي', 'موظف أهلي'), ('طالب', 'طالب'), ('مهندس', 'مهندس'), ('طبيب', 'طبيب'), ('معلم', 'معلم'), ('طالب علم', 'طالب علم'), ('ممرض', 'ممرض'), ('ربة بيت', 'ربة بيت'), ('متسبب', 'متسبب'), ('تاجر', 'تاجر'), ('غير ذلك', 'غير ذلك')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10)),
                ('options_trip', models.CharField(choices=[('المدينة و مكة', 'المدينة و مكة')], max_length=20)),
                ('marital_status', models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب'), ('أعزب', 'أعزب'), ('مطلق', 'مطلق')], max_length=10)),
                ('address', models.CharField(choices=[('القديح', 'القديح'), ('القطيف', 'القطيف'), ('صفوى', 'صفوى'), ('سيهات', 'سيهات'), ('العوامية', 'العوامية'), ('الجارودية', 'الجارودية'), ('الجش', 'الجش'), ('الأوجام', 'الأوجام'), ('تاروت', 'تاروت'), ('أخرى', 'أخرى')], max_length=15)),
                ('alhajj', models.CharField(blank=True, choices=[('حج واجب  ( أحج لأول مرة )', 'حج واجب  ( أحج لأول مرة )'), ('حج مستحب ( حججت مسبقا )', 'حج مستحب ( حججت مسبقا )'), ('حج نيابي ( أحج نيابة عن غير )', 'حج نيابي ( أحج نيابة عن غير )'), ('تاروت', 'تاروت'), ('عما في الذمة ( أحج لبراءة ذمتي )', 'عما في الذمة ( أحج لبراءة ذمتي )')], max_length=50, null=True)),
                ('tradition_reference', models.CharField(choices=[('الشيخ السيستاني', 'الشيخ السيستاني'), ('الشيخ الخوئي', 'الشيخ الخوئي'), ('الشيخ الوحيد', 'الشيخ الوحيد'), ('السيد الخامنئي', 'السيد الخامنئي'), ('السيد الحكيم', 'السيد الحكيم'), ('السيد صادق الشيرازي', 'السيد صادق الشيرازي'), ('السيد محمد الشيرازي', 'السيد محمد الشيرازي'), ('الشيخ الفياض', 'الشيخ الفياض'), ('الشيخ العصفور', 'الشيخ العصفور'), ('الشيخ أمين زين الدين', 'الشيخ أمين زين الدين'), ('الشيخ المدرسي', 'الشيخ المدرسي')])),
                ('count_hajjas', models.BigIntegerField(blank=True, null=True)),
                ('last_year', models.CharField(blank=True, null=True)),
                ('means_journey', models.CharField(choices=[('طيران ذهاب وعودة', 'طيران ذهاب وعودة'), ('ذهاب (طيران) والعودة (حافلة)', 'ذهاب (طيران) والعودة (حافلة)'), ('ذهاب (حافلة) والعودة (طيران)', 'ذهاب (حافلة) والعودة (طيران)'), ('حافلة ذهاب وعودة', 'حافلة ذهاب وعودة')], max_length=50)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], null=True)),
                ('illness', models.BooleanField(blank=True, null=True)),
                ('chronic_diseases', models.CharField(blank=True, max_length=200, null=True)),
                ('tawaf', models.BooleanField(blank=True, null=True)),
                ('sai', models.BooleanField(blank=True, null=True)),
                ('wheelchair', models.BooleanField(blank=True, null=True)),
                ('type_help', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(default='images/account.jpg', upload_to='images/users')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('get_notifications', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GuidancePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('cover', models.ImageField(upload_to='cover')),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guidancecategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guide')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pilgrim')),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('cover', models.ImageField(upload_to='cover')),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.religiouscategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('content', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=base.utils.get_expiration_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
