# Generated by Django 5.0.4 on 2024-04-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilgrim',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='pilgrim',
            name='borading_time',
        ),
        migrations.RemoveField(
            model_name='pilgrim',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='pilgrim',
            name='duration',
        ),
        migrations.AddField(
            model_name='customuser',
            name='get_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='gate_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='room_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
