# Generated by Django 5.0.4 on 2024-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_managers_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
