# Generated by Django 5.0.4 on 2024-04-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_pilgrim_arrive_remove_pilgrim_borading_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='get_notification',
            new_name='get_notifications',
        ),
    ]
