# Generated by Django 5.0.4 on 2024-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_guidancecategory_religiouscategory_guidancepost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الرحلة'),
        ),
    ]
