# Generated by Django 5.0.4 on 2024-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_get_notification_customuser_get_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='UserNotification',
        ),
    ]
