# Generated by Django 5.0.4 on 2024-04-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pilgrim_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReligious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='guidance')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type_guidance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typeguidance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReligiousWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='religious')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type_religious', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typereligious')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
