# Generated by Django 5.0.4 on 2024-04-15 14:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_guidancecategory_created_guide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(choices=[('القديح', 'القديح'), ('القطيف', 'القطيف'), ('صفوى', 'صفوى'), ('سيهات', 'سيهات'), ('العوامية', 'العوامية'), ('الجارودية', 'الجارودية'), ('الجش', 'الجش'), ('الأوجام', 'الأوجام'), ('تاروت', 'تاروت'), ('أخرى', 'أخرى')], max_length=15, verbose_name='مكان السكن'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='alhajj',
            field=models.CharField(blank=True, choices=[('حج واجب  ( أحج لأول مرة )', 'حج واجب  ( أحج لأول مرة )'), ('حج مستحب ( حججت مسبقا )', 'حج مستحب ( حججت مسبقا )'), ('حج نيابي ( أحج نيابة عن غير )', 'حج نيابي ( أحج نيابة عن غير )'), ('تاروت', 'تاروت'), ('عما في الذمة ( أحج لبراءة ذمتي )', 'عما في الذمة ( أحج لبراءة ذمتي )')], max_length=50, null=True, verbose_name='نوع الحجة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birthday',
            field=models.DateField(verbose_name='الميلاد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], null=True, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='chronic_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='أمراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='count_hajjas',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='عدد الحجات'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grand_father',
            field=models.CharField(max_length=50, verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_number',
            field=models.IntegerField(verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='illness',
            field=models.BooleanField(blank=True, null=True, verbose_name='أمراض'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='job_position',
            field=models.CharField(blank=True, choices=[('موظف حكومي', 'حكومي'), ('موظف شركة', 'موظف'), ('موظف أهلي', 'موظف أهلي'), ('طالب', 'طالب'), ('مهندس', 'مهندس'), ('طبيب', 'طبيب'), ('معلم', 'معلم'), ('طالب علم', 'طالب علم'), ('ممرض', 'ممرض'), ('ربة بيت', 'ربة بيت'), ('متسبب', 'متسبب'), ('تاجر', 'تاجر'), ('غير ذلك', 'غير ذلك')], max_length=50, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='العائلة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_year',
            field=models.CharField(blank=True, null=True, verbose_name='اخر سنة حج'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب'), ('أعزب', 'أعزب'), ('مطلق', 'مطلق')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='means_journey',
            field=models.CharField(choices=[('طيران ذهاب وعودة', 'طيران ذهاب وعودة'), ('ذهاب (طيران) والعودة (حافلة)', 'ذهاب (طيران) والعودة (حافلة)'), ('ذهاب (حافلة) والعودة (طيران)', 'ذهاب (حافلة) والعودة (طيران)'), ('حافلة ذهاب وعودة', 'حافلة ذهاب وعودة')], max_length=50, verbose_name='وسيلة الرحلة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='options_trip',
            field=models.CharField(choices=[('المدينة و مكة', 'المدينة و مكة')], max_length=20, verbose_name='خيارات الرحلة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sai',
            field=models.BooleanField(blank=True, null=True, verbose_name='مساعدة في السعي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tawaf',
            field=models.BooleanField(blank=True, null=True, verbose_name='مساعدة في الطواف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tradition_reference',
            field=models.CharField(choices=[('الشيخ السيستاني', 'الشيخ السيستاني'), ('الشيخ الخوئي', 'الشيخ الخوئي'), ('الشيخ الوحيد', 'الشيخ الوحيد'), ('السيد الخامنئي', 'السيد الخامنئي'), ('السيد الحكيم', 'السيد الحكيم'), ('السيد صادق الشيرازي', 'السيد صادق الشيرازي'), ('السيد محمد الشيرازي', 'السيد محمد الشيرازي'), ('الشيخ الفياض', 'الشيخ الفياض'), ('الشيخ العصفور', 'الشيخ العصفور'), ('الشيخ أمين زين الدين', 'الشيخ أمين زين الدين'), ('الشيخ المدرسي', 'الشيخ المدرسي')], verbose_name='مرجع التقليد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type_help',
            field=models.TextField(blank=True, null=True, verbose_name='نوع المساعدة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wheelchair',
            field=models.BooleanField(blank=True, null=True, verbose_name='كرسي متحرك'),
        ),
    ]
