# Generated by Django 5.0.4 on 2024-04-15 14:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_registration_address_alter_registration_alhajj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='arrival',
            field=models.DateTimeField(verbose_name='موعد الوصول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='birthday',
            field=models.DateField(verbose_name='الميلاد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='borading_time',
            field=models.TimeField(verbose_name='وقت الصعود'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='company_logo',
            field=models.ImageField(upload_to='', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='departure',
            field=models.DateTimeField(verbose_name='موعد الاقلاع'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='duration',
            field=models.DurationField(verbose_name='مدة الرحلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_company',
            field=models.CharField(max_length=50, verbose_name='رقم الرحلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='gate_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم البوابة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='grand_father',
            field=models.CharField(max_length=50, verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفندق'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='hotel_address',
            field=models.CharField(max_length=100, verbose_name='عنوان الفندق'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='العائلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='registeration_id',
            field=models.CharField(max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='room_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الغرفة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
