# Generated by Django 5.0.4 on 2024-04-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_pilgrim_arrival_alter_pilgrim_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhkamAlmrah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'أحكام عمرة',
                'verbose_name_plural': 'أحكام العمرة',
            },
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='ahkamalmrah',
            field=models.ManyToManyField(to='base.ahkamalmrah'),
        ),
        migrations.CreateModel(
            name='TypeAhkamAlmrah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('description', models.TextField(verbose_name='وصف')),
                ('ahkamalmrah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ahkamalmrah')),
            ],
        ),
    ]
