# Generated by Django 5.0.4 on 2024-04-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_hajsteps_steptype_pilgrim_haj_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hajsteps',
            name='step_type',
        ),
        migrations.DeleteModel(
            name='StepType',
        ),
    ]
