# Generated by Django 5.0.4 on 2024-04-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_hajsteps_step_type_delete_steptype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hajsteps',
            options={'verbose_name': 'عمل ديني', 'verbose_name_plural': 'أعمال دينية'},
        ),
    ]
