# Generated by Django 5.0.4 on 2024-04-17 18:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'استمارة تسجيل', 'verbose_name_plural': 'استمارات التسجيل'},
        ),
        migrations.AddField(
            model_name='usernotification',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معلومات اضافية'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat', verbose_name='المحادثة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=500, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='employee',
            field=models.BooleanField(default=False, verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_notifications',
            field=models.BooleanField(default=True, verbose_name='تلقي اشعارات'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/account.jpg', upload_to='images/users', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التوثيق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='guidancecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='guidancecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guidancecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='cover',
            field=models.ImageField(upload_to='cover', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='additional_info',
            field=models.CharField(max_length=300, verbose_name='رابط معلومات'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الخطوة'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=500, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='note',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guide', verbose_name='المرشد'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pilgrim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pilgrim', verbose_name='الحاج'),
        ),
        migrations.AlterField(
            model_name='religiouscategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='religiouscategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.religiouscategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='cover',
            field=models.ImageField(upload_to='cover', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='اكتملت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=100, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='اسم المهمة'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='content',
            field=models.CharField(max_length=200, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(max_length=50, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
