# Generated by Django 5.0.4 on 2024-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_secondarysteps_hajsteps_secondary_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarysteps',
            name='note',
            field=models.CharField(default='note', max_length=500),
        ),
    ]
