# Generated by Django 5.0.4 on 2024-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_secondarysteps_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondarysteps',
            options={'verbose_name': 'خطوة فرعية', 'verbose_name_plural': 'خطوات فرعية'},
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='secondary_steps',
            field=models.ManyToManyField(to='base.secondarysteps', verbose_name='خطوات فرعية'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='note',
            field=models.CharField(default='note', max_length=500, verbose_name='ملاحظة'),
        ),
    ]
