# Generated by Django 5.0.4 on 2024-04-28 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_hajsteps_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
