# Generated by Django 5.0.4 on 2024-05-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد الوصول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد الاقلاع'),
        ),
    ]
