# Generated by Django 5.0.4 on 2024-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_pilgrim_arrival_alter_pilgrim_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_company',
            field=models.CharField(max_length=50, verbose_name='اسم الشركة'),
        ),
    ]
