# Generated by Django 5.0.4 on 2024-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_pilgrim_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('content', models.CharField(max_length=200, verbose_name='المحتوى')),
                ('info', models.CharField(max_length=200, verbose_name='معلومات اضافية')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
    ]
