# Generated by Django 5.0.4 on 2024-05-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_basenotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='employee',
            new_name='sent_user',
        ),
        migrations.AlterField(
            model_name='registration',
            name='job_position',
            field=models.CharField(blank=True, choices=[('موظف حكومي', 'موظف حكومي'), ('موظف شركة', 'موظف شركة'), ('موظف أهلي', 'موظف أهلي'), ('طالب', 'طالب'), ('مهندس', 'مهندس'), ('طبيب', 'طبيب'), ('معلم', 'معلم'), ('طالب علم', 'طالب علم'), ('ممرض', 'ممرض'), ('ربة بيت', 'ربة بيت'), ('متسيب', 'متسيب'), ('تاجر', 'تاجر'), ('غير ذلك', 'غير ذلك')], max_length=50, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tradition_reference',
            field=models.CharField(choices=[('الشيخ السيستاني', 'الشيخ السيستاني'), ('الشيخ الخوئي', 'الشيخ الخوئي'), ('الشيخ الوحيد', 'الشيخ الوحيد'), ('السيد الخامنئي', 'السيد الخامنئي'), ('السيد الحكيم', 'السيد الحكيم'), ('السيد صادق الشيرازي', 'السيد صادق الشيرازي'), ('السيد محمد الشيرازي', 'السيد محمد الشيرازي'), ('الشيخ الفياض', 'الشيخ الفياض'), ('الشيخ العصفور', 'الشيخ العصفور'), ('الشيخ أمين زين الدين', 'الشيخ أمين زين الدين'), ('الشيخ المدرسي', 'الشيخ     ')], verbose_name='مرجع التقليد'),
        ),
    ]
