# Generated by Django 5.0.4 on 2024-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_chat_chat_type_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='الميلاد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='borading_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الصعود'),
        ),
    ]
