# Generated by Django 5.0.4 on 2024-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_pilgrim_birthday_alter_pilgrim_borading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='from_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='من المدينة'),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='to_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='إلى المدينة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_user',
            field=models.BooleanField(default=False, verbose_name='المستخدم'),
        ),
    ]
