# Generated by Django 5.0.4 on 2024-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_pilgrim_from_city_pilgrim_to_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilgrim',
            old_name='borading_time',
            new_name='boarding_time',
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='flight_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرحلة'),
        ),
    ]
