# Generated by Django 5.0.4 on 2024-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_borading_time_pilgrim_boarding_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الرحلة'),
        ),
    ]
