# Generated by Django 5.0.4 on 2024-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
    ]
