# Generated by Django 5.0.4 on 2024-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='arrival',
            field=models.TimeField(blank=True, null=True, verbose_name='موعد الوصول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='departure',
            field=models.TimeField(blank=True, null=True, verbose_name='موعد الاقلاع'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type_help',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع المساعدة'),
        ),
    ]
