# Generated by Django 5.0.4 on 2024-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_pilgrim_arrival_alter_pilgrim_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='company_logo',
            field=models.ImageField(blank=True, default='images/account.jpg', null=True, upload_to='', verbose_name='شعار الشركة'),
        ),
    ]
