# Generated by Django 5.0.4 on 2024-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_pilgrim_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مدة الرحلة'),
        ),
    ]
