# Generated by Django 5.0.4 on 2024-05-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_pilgrim_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='active_now',
            field=models.BooleanField(default=False),
        ),
    ]
