# Generated by Django 5.0.4 on 2024-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_pilgrim_active_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='duration',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='مدة الرحلة'),
        ),
    ]
