# Generated by Django 5.0.4 on 2024-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_pilgrim_guide_alter_registration_tradition_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('حاج', 'حاج'), ('مرشد', 'مرشد'), ('اداري', 'اداري'), ('موظف', 'موظف')], max_length=30, null=True),
        ),
    ]
