# Generated by Django 5.0.4 on 2024-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_pilgrim_guide_alter_registration_tradition_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('حاج', 'حاج'), ('مرشد', 'مرشد'), ('اداري', 'اداري'), ('موظف', 'موظف')], max_length=30)),
            ],
        ),
    ]
