# Generated by Django 5.0.4 on 2024-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilgrim',
            name='active_now',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_now',
            field=models.BooleanField(default=False),
        ),
    ]
