# Generated by Django 5.0.4 on 2024-05-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_pilgrim_active_now_customuser_active_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.guide', verbose_name='المرشد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='options_trip',
            field=models.CharField(choices=[('المدينة و مكة', 'المدينة و مكة'), ('مكة فقط', 'مكة فقط')], max_length=20, verbose_name='خيارات الرحلة'),
        ),
    ]
