# Generated by Django 5.0.4 on 2024-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('حاج', 'حاج'), ('مرشد', 'مرشد'), ('اداري', 'اداري'), ('موظف', 'موظف')], max_length=30),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
