# Generated by Django 5.0.4 on 2024-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_secondarysteps_note_hajsteps_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hajsteps',
            name='note',
        ),
        migrations.AddField(
            model_name='secondarysteps',
            name='note',
            field=models.TextField(default='default'),
        ),
    ]
