# Generated by Django 5.0.4 on 2024-05-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_secondarysteps_note_hajsteps_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilgrim',
            name='haj_steps',
        ),
        migrations.CreateModel(
            name='HaJStepsPilgrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('haj_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hajsteps')),
                ('pilgrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pilgrim')),
            ],
        ),
    ]
