# Generated by Django 5.0.4 on 2024-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_pilgrim_haj_steps_hajstepspilgrim'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='haj_steps',
            field=models.ManyToManyField(blank=True, through='base.HaJStepsPilgrim', to='base.hajsteps', verbose_name='خطوات الحملة'),
        ),
    ]
