# Generated by Django 5.0.4 on 2024-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_pilgrim_haj_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarysteps',
            name='note',
            field=models.CharField(default='note', max_length=500, verbose_name='ملاحظة'),
        ),
    ]
