# Generated by Django 5.0.4 on 2024-05-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_hajsteps_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hajsteps',
            options={'ordering': ['rank'], 'verbose_name': 'خطوة', 'verbose_name_plural': 'خطوات الأعمال الديني'},
        ),
    ]
