# Generated by Django 5.0.4 on 2024-06-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_hajsteps_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='rank',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
