# Generated by Django 5.0.4 on 2024-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_customuser_phonenumber_alter_hajsteps_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
