# Generated by Django 5.0.4 on 2024-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
