# Generated by Django 5.0.4 on 2024-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_customuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.IntegerField(unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.IntegerField(unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
