# Generated by Django 5.0.4 on 2024-06-03 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_pilgrim_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')], verbose_name='رقم الهاتف'),
        ),
    ]
