# Generated by Django 5.0.4 on 2024-06-06 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_customuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancepost',
            name='rank',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='religiouspost',
            name='rank',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
    ]
