# Generated by Django 5.0.4 on 2024-06-06 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_guidancepost_rank_alter_religiouspost_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancepost',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
    ]
