# Generated by Django 5.0.4 on 2024-06-08 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_guidancepost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.CharField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{5,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
