# Generated by Django 5.0.4 on 2024-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_pilgrim_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/pilgrims'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='المحتوى'),
        ),
    ]
