# Generated by Django 5.0.4 on 2024-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_note_audio_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrim',
            name='latitude',
            field=models.FloatField(default=45.2, max_length=100),
        ),
        migrations.AddField(
            model_name='pilgrim',
            name='longitude',
            field=models.FloatField(default=24.3, max_length=100),
        ),
    ]
