# Generated by Django 5.0.4 on 2024-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_chatmessage_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/chats'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='المحتوى'),
        ),
    ]
