# Generated by Django 5.0.4 on 2024-11-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_chatmessage_audio_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='sentBy',
            field=models.ForeignKey(default=622, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
