# Generated by Django 5.1.3 on 2024-12-25 08:41

import base.utils.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_note_audio_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioattach',
            name='file',
            field=models.FileField(upload_to='audio/chats', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='content',
            field=models.CharField(max_length=200, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='info',
            field=models.CharField(max_length=200, verbose_name='معلومات'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='sentBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مرسل من'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('guide', 'guide'), ('manager', 'manager')], default='guide', max_length=20, verbose_name='نوع المحادثة'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.audioattach', verbose_name='الصوت'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat', verbose_name='المحادثة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='مشاهدة'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_user',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_now',
            field=models.BooleanField(default=False, verbose_name='نشط الآن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='get_notifications',
            field=models.BooleanField(default=True, verbose_name='تلقي الإشعارات'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/account.jpg', upload_to='images/users', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{5,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('حاج', 'حاج'), ('مرشد', 'مرشد'), ('اداري', 'اداري'), ('موظف', 'موظف')], max_length=30, null=True, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='guidancecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='guidancecategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guidancecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='cover',
            field=models.ImageField(upload_to='cover', verbose_name='الغلاف'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='guidancepost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='note',
            field=models.CharField(default='note', max_length=500, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='hajsteps',
            name='secondary_steps',
            field=models.ManyToManyField(to='base.secondarysteps', verbose_name='الخطوات الثانوية'),
        ),
        migrations.AlterField(
            model_name='hajstepspilgrim',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='مكتمل'),
        ),
        migrations.AlterField(
            model_name='hajstepspilgrim',
            name='haj_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hajsteps', verbose_name='خطوة الحج'),
        ),
        migrations.AlterField(
            model_name='hajstepspilgrim',
            name='pilgrim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pilgrim', verbose_name='الحاج'),
        ),
        migrations.AlterField(
            model_name='management',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='arrival',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الوصول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='boarding_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الصعود'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='company_logo',
            field=models.ImageField(blank=True, default='images/account.jpg', null=True, upload_to='', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='departure',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت المغادرة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='duration',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='المدة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_company',
            field=models.CharField(max_length=50, verbose_name='شركة الطيران'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الرحلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='flight_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الرحلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='from_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='من مدينة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='gate_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم البوابة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='grand_father',
            field=models.CharField(max_length=50, verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.guide', verbose_name='المرشد'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='haj_steps',
            field=models.ManyToManyField(blank=True, through='base.HaJStepsPilgrim', to='base.hajsteps', verbose_name='خطوات الحج'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفندق'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='hotel_address',
            field=models.CharField(max_length=100, verbose_name='عنوان الفندق'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='latitude',
            field=models.FloatField(default=45.2, max_length=100, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='longitude',
            field=models.FloatField(default=24.3, max_length=100, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='phonenumber',
            field=models.CharField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{5,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='registeration_id',
            field=models.CharField(max_length=50, verbose_name='رقم التسجيل'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='room_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الغرفة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='to_city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='إلى مدينة'),
        ),
        migrations.AlterField(
            model_name='pilgrim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(choices=[('القديح', 'القديح'), ('القطيف', 'القطيف'), ('صفوى', 'صفوى'), ('سيهات', 'سيهات'), ('العوامية', 'العوامية'), ('الجارودية', 'الجارودية'), ('الجش', 'الجش'), ('الأوجام', 'الأوجام'), ('تاروت', 'تاروت'), ('أخرى', 'أخرى')], max_length=15, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='alhajj',
            field=models.CharField(blank=True, choices=[('حج واجب  ( أحج لأول مرة )', 'حج واجب  ( أحج لأول مرة )'), ('حج مستحب ( حججت مسبقا )', 'حج مستحب ( حججت مسبقا )'), ('حج نيابي ( أحج نيابة عن غير )', 'حج نيابي ( أحج نيابة عن غير )'), ('تاروت', 'تاروت'), ('عما في الذمة ( أحج لبراءة ذمتي )', 'عما في الذمة ( أحج لبراءة ذمتي )')], max_length=50, null=True, verbose_name='نوع الحج'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birthday',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], null=True, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='count_hajjas',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='عدد مرات الحج'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grand_father',
            field=models.CharField(max_length=50, verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id_number',
            field=models.IntegerField(verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='illness',
            field=models.BooleanField(blank=True, null=True, verbose_name='مريض'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='job_position',
            field=models.CharField(blank=True, choices=[('موظف حكومي', 'موظف حكومي'), ('موظف شركة', 'موظف شركة'), ('موظف أهلي', 'موظف أهلي'), ('طالب', 'طالب'), ('مهندس', 'مهندس'), ('طبيب', 'طبيب'), ('معلم', 'معلم'), ('طالب علم', 'طالب علم'), ('ممرض', 'ممرض'), ('ربة بيت', 'ربة بيت'), ('متسيب', 'متسيب'), ('تاجر', 'تاجر'), ('غير ذلك', 'غير ذلك')], max_length=50, null=True, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_year',
            field=models.CharField(blank=True, null=True, verbose_name='آخر سنة حج'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='marital_status',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('أعزب', 'أعزب'), ('مطلق', 'مطلق')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='means_journey',
            field=models.CharField(choices=[('طيران ذهاب وعودة', 'طيران ذهاب وعودة'), ('ذهاب (طيران) والعودة (حافلة)', 'ذهاب (طيران) والعودة (حافلة)'), ('ذهاب (حافلة) والعودة (طيران)', 'ذهاب (حافلة) والعودة (طيران)'), ('حافلة ذهاب وعودة', 'حافلة ذهاب وعودة')], max_length=50, verbose_name='وسيلة السفر'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='options_trip',
            field=models.CharField(choices=[('المدينة و مكة', 'المدينة و مكة'), ('مكة فقط', 'مكة فقط')], max_length=20, verbose_name='خيارات الرحلة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{5,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sai',
            field=models.BooleanField(blank=True, null=True, verbose_name='سعي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tawaf',
            field=models.BooleanField(blank=True, null=True, verbose_name='طواف'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tradition_reference',
            field=models.CharField(verbose_name='المرجع التقليدي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type_help',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع المساعدة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wheelchair',
            field=models.BooleanField(blank=True, null=True, verbose_name='كرسي متحرك'),
        ),
        migrations.AlterField(
            model_name='religiouscategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='religiouscategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.religiouscategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='cover',
            field=models.ImageField(upload_to='cover', verbose_name='الغلاف'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='religiouspost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='secondarysteps',
            name='note',
            field=models.CharField(default='note', max_length=500, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='مكتمل'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=100, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='content',
            field=models.CharField(max_length=200, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معلومات'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(max_length=50, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='password',
            field=models.CharField(max_length=100, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='phonenumber',
            field=models.CharField(max_length=100, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='username',
            field=models.CharField(max_length=100, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='رمز التحقق'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=base.utils.utils.get_expiration_time, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
