# Generated by Django 5.1.3 on 2024-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_audioattach_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/users/account.jpg', upload_to='images/users', verbose_name='الصورة'),
        ),
    ]
