# Generated by Django 5.1.3 on 2025-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='additional',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='كتابة المرافق معاك'),
        ),
    ]
