# Generated by Django 5.1.3 on 2025-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0076_termsandconditions_alter_registration_additional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="id_number",
            field=models.BigIntegerField(verbose_name="رقم الهوية"),
        ),
    ]
