# Generated by Django 5.1.3 on 2025-03-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0077_alter_registration_id_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basenotification",
            name="info",
        ),
    ]
