# Generated by Django 5.1.3 on 2025-03-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0078_remove_basenotification_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPassword",
        ),
    ]
