# Generated by Django 5.1.3 on 2025-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0082_remove_livestream_description_livestream_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
    ]
