# Generated by Django 5.1.3 on 2025-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0086_pilgrim_email_alter_registration_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilgrim",
            name="email",
            field=models.EmailField(
                blank=True,
                default="Info@alnoor-hajj.com",
                max_length=254,
                null=True,
                verbose_name="الايميل",
            ),
        ),
    ]
