# Generated by Django 5.1.3 on 2025-04-18 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0087_alter_pilgrim_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registeration2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{5,15}$")
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="Info@alnoor-hajj.com",
                        max_length=254,
                        null=True,
                        verbose_name="الايميل",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="الاسم الأول"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="اسم العائلة"),
                ),
                ("id_number", models.BigIntegerField(verbose_name="رقم الهوية")),
                ("birthday", models.DateField(verbose_name="تاريخ الميلاد")),
            ],
        ),
    ]
