# Generated by Django 5.1.3 on 2025-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0088_registeration2"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeration2",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
    ]
