# Generated by Django 5.1.3 on 2025-05-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0089_registeration2_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilgrim",
            name="room_num",
            field=models.CharField(blank=True, null=True, verbose_name="رقم الغرفة"),
        ),
    ]
