# Generated by Django 5.1.3 on 2025-05-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0090_alter_pilgrim_room_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilgrim",
            name="room_num",
            field=models.IntegerField(blank=True, null=True, verbose_name="رقم الغرفة"),
        ),
    ]
