name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          debug: true  # Enable debug mode to get more information
          script: | 
            cd /home/al_noor/Al_Noor
            git fetch origin
            git rebase origin
            source env/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput 